# Generated by Django 5.1.7 on 2025-03-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_agentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
