# Generated by Django 5.1.7 on 2025-03-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_agentprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='profile_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
