# Generated by Django 5.1.7 on 2025-03-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_alter_agentprofile_profile_pictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='username',
            new_name='user',
        ),
    ]
