# Generated by Django 5.1.7 on 2025-03-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_rename_username_agentprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentProfile',
        ),
    ]
