# Generated by Django 5.1.7 on 2025-03-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_delete_agentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='seller_username',
            new_name='agent_phone',
        ),
        migrations.AddField(
            model_name='property',
            name='agent_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
