# Generated by Django 5.1.7 on 2025-03-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_baseproperty_commercialproperty_houseproperty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseproperty',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('selfcontain', 'Selfcontain'), ('bungalow', 'Bungalow'), ('studio', 'Studio Apartment'), ('duplex', 'Duplex'), ('triplex/fourplex', 'Triplex/Fourplex'), ('detached', 'Detached House'), ('semi-detached', 'Semi-Detached House'), ('mansion', 'Mansion'), ('townhouse', 'Townhouse')], max_length=20, null=True),
        ),
    ]
