# Generated by Django 5.1.7 on 2025-03-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0012_alter_houseproperty_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproperty',
            name='listing',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('rent', 'Rent'), ('shortlet', 'Shortlet')], max_length=255, null=True),
        ),
    ]
