# Generated by Django 5.1.7 on 2025-03-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0013_baseproperty_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialproperty',
            old_name='floor_level',
            new_name='floor_count',
        ),
    ]
