# Generated by Django 5.1.7 on 2025-03-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0014_rename_floor_level_commercialproperty_floor_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('selfcontain', 'Selfcontain'), ('bungalow', 'Bungalow'), ('studio', 'Studio Apartment'), ('duplex', 'Duplex'), ('triplex/fourplex', 'Triplex/Fourplex'), ('detached', 'Detached House'), ('semi-detached', 'Semi-Detached House'), ('mansion', 'Mansion'), ('townhouse', 'Townhouse'), ('office', 'Office Space'), ('shop', 'Shop'), ('workspace', 'Workspace'), ('warehouse', 'Warehouse'), ('land', 'Land')], max_length=20, null=True)),
                ('listing', models.CharField(blank=True, choices=[('buy', 'Buy'), ('rent', 'Rent'), ('shortlet', 'Shortlet')], max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented')], default='available', max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('floor_count', models.IntegerField(blank=True, null=True)),
                ('fence', models.CharField(choices=[('none', 'No Fence'), ('dwarf', 'Dwarf Fence'), ('full', 'Full Fence')], default='none', max_length=255)),
                ('gate', models.BooleanField(blank=True, default=False, null=True)),
                ('solar', models.BooleanField(blank=True, default=False, null=True)),
                ('measurement', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True)),
                ('agent_username', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('imagea', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('imageb', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('imagec', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('parking_space', models.BooleanField(blank=True, default=False, null=True)),
                ('unit', models.CharField(blank=True, choices=[('sq_ft', 'Square Feet'), ('sq_m', 'Square Meter')], max_length=255, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('garage', models.BooleanField(blank=True, default=False, null=True)),
                ('swimming_pool', models.BooleanField(blank=True, default=False, null=True)),
                ('elevator', models.BooleanField(blank=True, default=False, null=True)),
                ('restroom', models.BooleanField(blank=True, default=False, null=True)),
                ('land_unit', models.CharField(blank=True, choices=[('plots', 'Plots'), ('hectares', 'Hectares'), ('acres', 'Acres')], max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='houseproperty',
            name='baseproperty_ptr',
        ),
        migrations.RemoveField(
            model_name='landproperty',
            name='baseproperty_ptr',
        ),
        migrations.AlterField(
            model_name='whishlistitem',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.property'),
        ),
        migrations.DeleteModel(
            name='CommercialProperty',
        ),
        migrations.DeleteModel(
            name='BaseProperty',
        ),
        migrations.DeleteModel(
            name='LandProperty',
        ),
        migrations.DeleteModel(
            name='HouseProperty',
        ),
    ]
