# Generated by Django 5.1.7 on 2025-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0015_property_remove_houseproperty_baseproperty_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='elevator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_space',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='restroom',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='solar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='swimming_pool',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
