# Generated by Django 5.1.7 on 2025-04-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0016_alter_property_elevator_alter_property_garage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='duration',
            field=models.CharField(blank=True, choices=[('Per Annum', 'per_annum'), ('Per Month', 'Per_month'), ('Per Day', 'Per_day')], max_length=20, null=True),
        ),
    ]
